version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
